### ISSUE TITLE
serviceAccount Issue

### ISSUE THREAD

**Issue by Kronhyx** [OhioUniversityRevUC2020/APIServer#5]
Hi, I came to this repository by chance,
and I see that we are doing something similar with typedi and express

but I wanted to comment that it is a security flaw to versionate your serviceAccount

I think you should consider using github secrets

regards

**Comment by BlenderDude** [comment]
Any key that is in this repo is already deactivated. Because this was created at a hackathon, security was not our biggest concern. I deleted them from the repo to alleviate confusion.
